import os
import subprocess
import json
import sys
import re

# Configuration
NOTES_BASE_DIR = r"C:\Users\Putu Ari\note-taking-app\data\notes\Knowledge\VideoSummaries"
NOTEBOOKLM_EXE = r"C:\Users\Putu Ari\AppData\Roaming\Python\Python314\Scripts\notebooklm.exe"

def run_command(command):
    try:
        result = subprocess.run(command, capture_output=True, text=True, check=True, shell=True)
        return result.stdout
    except subprocess.CalledProcessError as e:
        print(f"Error executing command: {e}")
        print(f"Stdout: {e.stdout}")
        print(f"Stderr: {e.stderr}")
        return None

def sanitize_filename(name):
    return re.sub(r'[\\/*?:"<>|]', "", name).strip()

def process_video(video_url):
    print(f"--- Processing Video: {video_url} ---")
    
    # 1. Create Notebook
    notebook_title = f"Video Summary: {video_url.split('=')[-1]}"
    create_cmd = f'"{NOTEBOOKLM_EXE}" create "{notebook_title}" --json'
    create_output = run_command(create_cmd)
    if not create_output: return
    
    notebook_data = json.loads(create_output)
    notebook_id = notebook_data['notebook']['id']
    print(f"Created Notebook: {notebook_id}")

    # 2. Add Source (with retry)
    video_title = None
    source_id = None
    max_retries = 3
    for i in range(max_retries):
        print(f"Adding Source (Attempt {i+1})...")
        add_src_cmd = f'"{NOTEBOOKLM_EXE}" source add "{video_url}" --notebook "{notebook_id}" --json'
        add_src_output = run_command(add_src_cmd)
        if add_src_output:
            source_data = json.loads(add_src_output)
            if 'source' in source_data:
                source_id = source_data['source']['id']
                video_title = source_data['source']['title']
                break
        print("Retrying in 5 seconds...")
        import time
        time.sleep(5)

    if not source_id:
        print("Failed to add source after retries.")
        return
    
    print(f"Added Source: {video_title} ({source_id})")

    # 3. Wait for Source
    print("Waiting for source to be ready...")
    wait_cmd = f'"{NOTEBOOKLM_EXE}" source wait "{source_id}" --notebook "{notebook_id}" --timeout 300'
    run_command(wait_cmd)

    # 4. Ask for Summary
    print("Generating summary...")
    ask_cmd = f'"{NOTEBOOKLM_EXE}" ask "Tolong berikan ringkasan yang sangat mendalam dan terstruktur dari video ini dalam Bahasa Indonesia. Fokus pada ide-ide kunci, strategi yang dibahas, dan kesimpulan praktis yang bisa diambil." --notebook "{notebook_id}" --json'
    ask_output = run_command(ask_cmd)
    if not ask_output: return
    
    summary_data = json.loads(ask_output)
    summary_text = summary_data['answer']

    # 5. Save to Local Note Taking System
    folder_name = sanitize_filename(video_title)
    folder_path = os.path.join(NOTES_BASE_DIR, folder_name)
    os.makedirs(folder_path, exist_ok=True)
    
    note_path = os.path.join(folder_path, "Summary.md")
    with open(note_path, "w", encoding="utf-8") as f:
        f.write(f"# {video_title}\n\n")
        f.write(f"**URL:** {video_url}\n\n")
        f.write("## Ringkasan\n\n")
        f.write(summary_text)
        f.write("\n\n---\n*Generated by NotebookLM Automation*")

    print(f"--- Successfully saved note to: {note_path} ---")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python import_video_note.py <video_url>")
    else:
        process_video(sys.argv[1])
